config/routes.rb
Rails.application.routes.draw do

 # 顧客用ルート

  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
   #homesコントローラ
  root to: "homes#top"
  get 'homes/about' => 'homes#about'

    #cutomersコントローラ
   get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/my_page/edit' => 'customers#edit'
   patch 'customers/update' => 'customers#update'

    #ordersコントローラ
   post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
   get 'orders/thank' => 'orders#thank'
   resources :orders, only: [:create, :new, :index, :show ,:confirm]

    #itemsコントローラ
   resources :items, only: [:index, :show]

    #cart_itemsコントローラ
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :cart_items, only: [:index, :create, :update, :destroy]

    #deriveriesコントローラ
   resources :deriveries, only: [:index, :create, :destroy, :edit, :update]

   get 'item_search', to: 'searches#item_search'
  end



 # 管理者用ルート
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :admin do
   root :to => 'homes#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:show, :update, :index]
   resources :order_details, only: [:update]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details


  validates :name, presence: true
  validates :item_introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [true, false]

  def taxin_price
    (self.price * 1.10).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:notice] = "商品を追加しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "商品を追加できませんでした。"
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash.now[:notice] = "編集内容を更新しました。"
      redirect_to action: 'index'
    else
      flash.now[:alert] = "入力内容を確認してください。"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :item_introduction, :price, :image, :genre_id, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container col-xs-6">
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><i class="fas fa-pen"></i> 商品編集</h4>
 　　</div>
 　</div>

 <div class="row">
    <div class="col-8 offset-2 md-5">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <%= f.label :商品画像, class:"form_label font-weight-bold" %><br>
            <%= f.attachment_field :image, class:"md-3 ml-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :商品名, class:"form_label font-weight-bold" %>
            <%= f.text_field :name, placeholder: "商品名", class:"form-control md-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :商品説明, class:"form_label font-weight-bold" %>
            <%= f.text_area :item_introduction, placeholder: "ここに説明文を記述します", class:"form-control form-control-lg mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :ジャンル, class:"form_label font-weight-bold" %>
            <%=  f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "--選択してください--"}, {class: "form-control"}) %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :税抜き価格, class:"form_label my-3 font-weight-bold" %><br>
            <%= f.text_field :price, size:"15" %>円
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :販売ステータス, class:"form_label my-3 font-weight-bold" %><br>
            <%= f.radio_button :is_active, true, checked: true %>
            <%= f.label :is_active, "販売中", class:"form_label" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", class:"form_label" %>
          </div>
        </tr>
        <tr>
          <div class="form-action d-flex justify-content-around">
            <%= f.submit "変更を保存する", class:"btn btn-success" %>
            <%= link_to "商品詳細へ戻る", admin_item_path, class:"btn btn-outline-secondary" %>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  
  <div class="row">
　　<div class="col-xs-10 mt-3">
 　　　<h4><i class="fas fa-cookie-bite"></i> 商品一覧</h4>
 　　</div>
    <div class="col-xs-2 offset-9 mt-5">
      <%= link_to new_admin_item_path, class:"btn btn-outline-secondary" do %>
        <i class="fas fa-plus fa-2x"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
      <table class="table table-light table-striped">
        <thead>
          <tr class="text-white bg-dark">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price %>円</td>
            <td><%= item.genre.name %></td>
            <td><%= item.is_active == true ? "販売中" : "販売停止中" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container col-xs-6">
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><i class="fas fa-shopping-cart"></i>商品新規登録</h4>
 　　</div>
    <div class="col-sm-10 px-sm-0 mx-auto md-5">
     <%= form_with model: [:admin, @item], local:true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.attachment_field :image %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <th><%= f.text_field :name, placeholder:"商品名" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <th><%= f.text_area :item_introduction, size: "50×5", placeholder:"ここに説明文を記述します" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル %></th>
            <th><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :税抜き価格 %></th>
            <th><%= f.text_field :price, placeholder:"1000" %>円</th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :販売ステータス %></th>
            <td>
              <%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
            </td>
          </div>
        </tr>
        <tr>
          <div class="form-action">
            <th><%= f.submit "新規登録", class:"btn btn-success" %></th>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container col-xs-6">
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><i class="fas fa-cookie-bite"></i> 商品詳細</h4>
 　　</div>
 　</div>

    <div class="row align-items-center m-5">
    <div class="col-lg text-center mb-5">
      <%= attachment_image_tag @item, :image, :fill, 500, 350, class:"icon border", fallback: "no_image.jpg" ,size:'350x300'%>
    </div>
    <div class="col-lg">
      <table class="table item-table">
        <tr>
          <th nowrap>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th nowrap>商品詳細</th>
          <td><%= @item.item_introduction %></td>
        </tr>
        <tr>
          <th nowrap>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th nowrap>税込価格<br>(税抜価格)</th>
          <td><%= (@item.price * 1.1).floor %> (<%= @item.price %>)円</td>
        </tr>
        <tr>
          <th nowrap>販売ステータス</th>
          <td>
           <%= @item.is_active == true ? "販売中" : "販売停止中" %>
          </td>
        </tr>
      </table>
      <div class="d-flex justify-content-around">
        <p><%= link_to "編集する",edit_admin_item_path(@item), class:"btn btn-success" %></p>
        <p><%= link_to "商品一覧へ戻る", admin_items_path, class:"btn btn-outline-secondary" %></p>
      </div>
    </div>
  </div>
</div>