config/routes.rb
Rails.application.routes.draw do

 # 顧客用ルート

  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
   #homesコントローラ
  root to: "homes#top"
  get 'homes/about' => 'homes#about'

    #cutomersコントローラ
   get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/my_page/edit' => 'customers#edit'
   patch 'customers/update' => 'customers#update'

    #ordersコントローラ
   post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
   get 'orders/thank' => 'orders#thank'
   resources :orders, only: [:create, :new, :index, :show ,:confirm]

    #itemsコントローラ
   resources :items, only: [:index, :show]

    #cart_itemsコントローラ
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :cart_items, only: [:index, :create, :update, :destroy]

    #deriveriesコントローラ
   resources :deriveries, only: [:index, :create, :destroy, :edit, :update]

   get 'item_search', to: 'searches#item_search'
  end



 # 管理者用ルート
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :admin do
   root :to => 'homes#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:show, :update, :index]
   resources :order_details, only: [:update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :deliveries, dependent: :destroy
 has_many :cart_items, dependent: :destroy

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :postcode, numericality: {only_integer: true} #数値のみ
  validates :address, presence: true
  validates :tel, numericality: {only_integer: true} #数値のみ
  validates :email, presence: true, uniqueness: true

  has_many :delivery, dependent: :destroy
  has_many :order, dependent: :destroy

  def full_name
    self.family_name + " " + self.first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postcode, :address, :tel, :is_registered)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container col-xs-6">
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><%= @customer.full_name %>さんの会員情報編集</h4>
 　　</div>
 </div>

    <div class="row ml-4 mt-3">
     <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
      <div class="form-group row">
        <div class="col-4">会員ID</div>
        <div class="col-8"><%= @customer.id %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><%= f.label :氏名 %></div>
        <div class="col-4"><%= f.text_field :family_name, class: "form-control" %></div>
        <div class="col-4"><%= f.text_field :first_name, class: "form-control" %></div>
      </div>
    
      <div class="form-group row">
        <div class="col-4"><%= f.label :フリガナ %></div>
        <div class="col-4"><%= f.text_field :family_name_kana, class: "form-control" %></div>
        <div class="col-4"><%= f.text_field :first_name_kana, class: "form-control" %></div>
      </div>
    
      <div class="form-group row">
        <div class="col-4"><%= f.label :郵便番号 %></div>
        <div class="col-8"><%= f.text_field :postcode, class: "form-control" %></div>
      </div>
    
      <div class="form-group row">
        <div class="col-4"><%= f.label :住所 %></div>
        <div class="col-8"><%= f.text_field :address, class: "form-control" %></div>
      </div>
    
      <div class="form-group row">
        <div class="col-4"><%= f.label :電話番号 %></div>
        <div class="col-8"><%= f.text_field :tel, class: "form-control" %></div>
      </div>
    
      <div class="form-group row">
        <div class="col-4"><%= f.label :メールアドレス %></div>
        <div class="col-8"><%= f.email_field :email, class: "form-control" %></div>
      </div>
    
      <div class="form-group row">
        <div class="col-4"><%= f.label :会員ステータス %></div>
        <div class="col-8">
          <%= f.radio_button :is_registered, true %>
          <%= f.label :is_registered, "有効", value: true %>
          <%= f.radio_button :is_registered, false %>
          <%= f.label :is_registered, "退会", value: false %>
        </div>
      </div>
    
      <div class="row">
        <div class="col-4"></div>
        <div class="col-8"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
      </div>
    <% end %>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container col-xs-6">
    <div class="row">
  　　<div class="col-xs-12 mt-3">
   　　　<h4><i class="fas fa-users"></i>会員一覧</h4>
   　　</div>
   　</div>
  
  <div class="row offset-2 col-8 mt-3">
    <table class="table table-light table-striped">
      <thead>
        <tr class="text-white bg-dark">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
  
      <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.full_name, admin_customer_path(customer), class: "text-dark", style: "text-decoration: underline" %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_registered? %>
              <span class="text-success"><strong>有効</strong></span>
            <% else %>
              <span class="text-secondary"><strong>退会</strong></span>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container col-xs-6">
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><%= @customer.full_name %>さんの会員詳細</h4>
 　　</div>
 </div>

  <div class="col-6 ml-4">

    <div class="row mt-3">
      <div class="col-4">会員ID</div>
      <div class="col-8"><%= @customer.id %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">氏名</div>
      <div class="col-8"><%= @customer.full_name %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">フリガナ</div>
      <div class="col-8"><%= @customer.family_name_kana %> <%= @customer.first_name_kana %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">郵便番号</div>
      <div class="col-8"><%= @customer.postcode %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">住所</div>
      <div class="col-8"><%= @customer.address %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">電話番号</div>
      <div class="col-8"><%= @customer.tel %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">メールアドレス</div>
      <div class="col-8"><%= @customer.email %></div>
    </div>

    <div class="row mt-3">
      <div class="col-4">会員ステータス</div>
      <div class="col-8">
        <% if @customer.is_registered? %>
          <div class="text-success"><strong>有効</strong></div>
        <% else %>
          <div class="text-secondary"><strong>退会</strong></div>
        <% end %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-4"></div>
      <div class="col-3"><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></div>
      <div class="col-5"><%= link_to "注文履歴一覧を見る", admin_orders_path(customer_id: @customer), class: "btn btn-primary" %></div>
    </div>
  </div>
</div>