config/routes.rb
Rails.application.routes.draw do

 # 顧客用ルート

  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
   #homesコントローラ
  root to: "homes#top"
  get 'homes/about' => 'homes#about'

    #cutomersコントローラ
   get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/my_page/edit' => 'customers#edit'
   patch 'customers/update' => 'customers#update'

    #ordersコントローラ
   post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
   get 'orders/thank' => 'orders#thank'
   resources :orders, only: [:create, :new, :index, :show ,:confirm]

    #itemsコントローラ
   resources :items, only: [:index, :show]

    #cart_itemsコントローラ
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :cart_items, only: [:index, :create, :update, :destroy]

    #deriveriesコントローラ
   resources :deriveries, only: [:index, :create, :destroy, :edit, :update]

   get 'item_search', to: 'searches#item_search'
  end



 # 管理者用ルート
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :admin do
   root :to => 'homes#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:show, :update, :index]
   resources :order_details, only: [:update]
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
  params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container col-xs-6">
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><i class="fas fa-tag"></i>ジャンル編集</h4>
 　　</div>
 　</div>

  <div class="row">
    <div class="col-8 mt-3">
      <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
      <div class="form-group row">
        <div class="col-2"><%= f.label :ジャンル名 %></div>
        <div class="col-4"><%= f.text_field :name %></div>
        <div class="col-3"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
      </div>
      <% end %>
    </div>
  </div>
 </div>

app/views/admin/genres/index.html.erb
<div class="container col-xs-6">
  
  <div class="row">
　　<div class="col-xs-12 mt-3">
 　　　<h4><i class="fas fa-tag"></i>ジャンル一覧・追加</h4>
 　　</div>
  </div>
  
  <div class="row">
    <div class="col-xs-10 mt-1">
      <%= form_with model: @genre, url:admin_genres_path, local: true do |f| %>
        <div class="form-group row">
          <div class="col-3"><%= f.label :ジャンル名 %></div>
          <div class="col-4"><%= f.text_field :name, placeholder: "ジャンル名" %></div>
          <div class="col-2 offset-1"><%= f.submit "新規登録", class: "btn btn-success" %></div>
        </div>
      <% end %>
    </div>
   </div>

    <div class="row mt-5">
      <div class="col-xs-12">
        <table class="table table-light">
          <thead class="table-active text-center">
            <tr>
              <th class="text-white bg-dark">ジャンル</th>
              <th class="text-white bg-dark"></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td class="text-center"><%= genre.name %></td>
              <td class="text-center"><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
 </div>