config/routes.rb
Rails.application.routes.draw do

 # 顧客用ルート

  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
   #homesコントローラ
  root to: "homes#top"
  get 'homes/about' => 'homes#about'

    #cutomersコントローラ
   get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/my_page/edit' => 'customers#edit'
   patch 'customers/update' => 'customers#update'

    #ordersコントローラ
   post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
   get 'orders/thank' => 'orders#thank'
   resources :orders, only: [:create, :new, :index, :show ,:confirm]

    #itemsコントローラ
   resources :items, only: [:index, :show]

    #cart_itemsコントローラ
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :cart_items, only: [:index, :create, :update, :destroy]

    #deriveriesコントローラ
   resources :deriveries, only: [:index, :create, :destroy, :edit, :update]

   get 'item_search', to: 'searches#item_search'
  end



 # 管理者用ルート
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :admin do
   root :to => 'homes#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:show, :update, :index]
   resources :order_details, only: [:update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         validates :email, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :quantity, numericality: {greater_than_or_equal_to:1,less_than_or_equal_to:10, message: '1回の注文は10個までです。' }
  
  def sum_taxin_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    (item.price*quantity*1.10).round
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :deliveries, dependent: :destroy
 has_many :cart_items, dependent: :destroy

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :postcode, numericality: {only_integer: true} #数値のみ
  validates :address, presence: true
  validates :tel, numericality: {only_integer: true} #数値のみ
  validates :email, presence: true, uniqueness: true

  has_many :delivery, dependent: :destroy
  has_many :order, dependent: :destroy

  def full_name
    self.family_name + " " + self.first_name
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord

  validates :postcode, presence: true
  validates :address, length: {minimum: 7}, presence: true
  validates :destination, presence: true

   belongs_to :customer

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details


  validates :name, presence: true
  validates :item_introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [true, false]

  def taxin_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  after_update :check_order_detail

  enum payment_method:{credit: 0,bank:1}
  enum order_status:{wait: 0, confirmation: 1, making: 2, preparation: 3, finish: 4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postcode,  presence: true
  validates :address, presence: true
  validates :destination, presence: true
  validates :payment_method, presence: true
  validates :billing_amount, presence: true

  def order_items_billing_amount
    (billing_amount - 800).round
  end

  private

   def check_order_detail
     if self.order_status == "confirmation"
       self.order_details.update_all(production_status: "wait")
     end
   end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  after_update :check_production_status

  enum production_status:{before: 0,wait:1,make:2,finish:3}

  belongs_to :order
  belongs_to :item

  private

  def check_production_status
    if self.production_status == "make"
      self.order.update(order_status: "making")
    elsif self.production_status == "finish"
      if self.order.order_details.all? { |order_detail| order_detail.production_status == "finish" }
        self.order.update(order_status: "preparation")
      end
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:notice] = "商品を追加しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "商品を追加できませんでした。"
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash.now[:notice] = "編集内容を更新しました。"
      redirect_to action: 'index'
    else
      flash.now[:alert] = "入力内容を確認してください。"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :item_introduction, :price, :image, :genre_id, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :postcode, :address, :tel])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",count: resource.errors.count,resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
　　<p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
　　<p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center">© 2022.01~ モンブラン</p>
  <div class="d-flex justify-content-center">
    <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
    <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
    <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
  </div>
</footer>

app/views/layouts/_genre.html.erb
<div class="box17">
  <p class="font-weight-bold">商品ジャンル</p>
    <% @genres.each do |genre| %>
      <p><%= genre.name %></p>
    <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
      <% if admin_signed_in? %>
          <%= link_to admin_root_path do %>
            <%= image_tag 'logo1.png', :size =>'120x120'%>
            <% end %>
      <% else %>
        <%= link_to root_path do %>
            <%= image_tag 'logo1.png' ,:size =>'120x120' %>
            <% end %>
      <% end %>
      <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav">
         <% if customer_signed_in? %>
          <li class="nav-item active">
           <span class="nav-link text-dark">ようこそ、<%= current_customer.family_name%>さん</span>
          </li>
            <%= link_to icon('fas','fas fa-user',"マイページ"), customers_my_page_path, class: "btn btn-outline-light mx-3 my-1"%>
          </li>
          <li class="nav-item ">
            <%= link_to icon('fas','cookie-bite',"商品一覧"), items_path,class: 'btn btn-outline-light mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to icon('fas','shopping-cart',"カート"), cart_items_path,class: 'btn btn-outline-light mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to icon('fas','sign-out-alt',"ログアウト"), destroy_customer_session_path, method: :delete ,class: 'btn btn-outline-light mx-3 my-1'%>
          </li>
         <% elsif admin_signed_in? %>
           <li class="nav-item">
             <%= link_to icon('fas','file-alt',"注文履歴一覧"), admin_root_path, class:'btn btn-outline-light mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','cookie-bite',"商品一覧"), admin_items_path,class: 'btn btn-outline-light mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','fas fa-folder',"ジャンル一覧"), admin_genres_path,class: 'btn btn-outline-light mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','user-circle',"会員一覧"), admin_customers_path, class:'btn btn-outline-light mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','sign-out-alt',"ログアウト"),destroy_admin_session_path, method: :delete,class: 'btn btn-outline-light mx-3 my-1'%>
           </li>
         <% else %>
         <li class="nav-item">
             <%= link_to icon('fas','fas fa-folder',"About"), homes_about_path,class: 'btn btn-outline-light mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','cookie-bite',"商品一覧"), items_path,class: 'btn btn-outline-light mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','user-plus',"新規登録"), new_customer_registration_path,class: 'btn btn-outline-light mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to icon('fas','sign-in-alt',"ログイン"), new_customer_session_path,class: 'btn btn-outline-light mx-3 my-1'%>
           </li>
          <% end %>
        </ul>
      </div>
      <%= render 'layouts/search' %>
 </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search">
<%= form_with url: item_search_path, method: :get, local: true do |form| %>
  <%= form.text_field :search %>
  <%= form.submit '検索' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://kit.fontawesome.com/c3fbb4b704.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
     <div id="wrapper">
        <%= render "layouts/header"%>
    <main>
     <div id="flash">
        <%= render "layouts/flash" %>
     </div>
      <div class="container">
      <%= yield %>
    </main>
    <%= render "layouts/footer"%>
    </div>
  　　<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
  　　<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
　　　<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </body>
</html>